### ISSUE TITLE
Clarify the meaning of "installing" a kernel extension

### ISSUE THREAD

**Issue by marnovo** [PMheart/LiluFriend#1]
In the [readme](https://github.com/PMheart/LiluFriend/) there is a mention about "installing" the modified kext:

> Save your edited Info.plist and install LiluFriend.kext to /Library/Extensions and /System/Library/Extensions

It is not clear if this mean just copying the .kext file(s, as does this include the LiluFriend plus the kexts wanted?) there or if there are any additional steps or processes involved (and if so, it would be nice to explain inline or link to somewhere that explains it). Thanks!

**Comment by PMheart** [comment]
Hi! Sorry for the late reply.
Of course, I assume that you've installed Lilu + plugins to /S/L/E or /L/E, thus, you only need to install LiluFriend additionally.

**Comment by PMheart** [comment]
Issue closed. Feel free to reopen it for further reports.
